# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-18 00:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('course', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=100)),
            ],
        ),
    ]
